name: Restart Tomcat Servers
on:
  workflow_dispatch:
 push:
   branches:
     - main  # Or any branch you want
jobs:
 deploy:
   runs-on: pg-pgi-16gb-4cpu
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.x'
     - name: Install Ansible
       run: |
         python -m pip install --upgrade pip
         pip install ansible
     - name: Add SSH key to agent
       uses: webfactory/ssh-agent@v0.7.0
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
     - name: Run Ansible Playbook
       run: |
         ansible-playbook -i inventory.yml tomcat_restart.yml
       env:
         ANSIBLE_HOST_KEY_CHECKING: 'false'
